### ISSUE TITLE
Fix installation instructions

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dbox#2]
At some point I decided that it is better that the DB is in a separate container, instead of being inside the dbox container. However these changes have not been reflected to the installation instructions (README.md). Fix it.
@docker-scripts/dbox-applicants

**Comment by niksen31** [comment]
Good morning Dashamari, I'm not currently on my computer but if I understand correctly we just have to create a directory for the database container and then:
start db container with
docker run --name proj -e MYSQL_ROOT_PASSWORD=proj -d mariadb:tag
link the two
docker run --name myproject --link proj:mysql 

I will give a try when I'm home.

**Comment by dashohoxha** [comment]
Nikos, no need to hurry.
Instructions for installing the DB are here: https://github.com/docker-scripts/mariadb#installation

**Comment by dashohoxha** [comment]
Fixed by https://github.com/docker-scripts/dbox/pull/3
