### ISSUE TITLE
Drush throwing some errors while installation

### ISSUE THREAD

**Issue by karshd3v** [docker-scripts/dbox#4]
PHP Fatal error:  Declaration of RulesRuleUI::form(&$form, &$form_state, $options = Array) must be compatible with RulesActionContainerUI::form(&$form, &$form_state, $options = Array, $iterator = NULL) in /var/www/proj/profiles/myproject/modules/contrib/rules/ui/ui.plugins.inc on line 80
Drush command terminated abnormally due to an unrecoverable error.                                [error]
Error: Declaration of RulesRuleUI::form(&$form, &$form_state,
$options = Array) must be compatible with
RulesActionContainerUI::form(&$form, &$form_state, $options = Array,
$iterator = NULL) in
/var/www/proj/profiles/myproject/modules/contrib/rules/ui/ui.plugins.inc,
line 80
+ drush='drush --root=/var/www/proj --yes'
+ drush --root=/var/www/proj --yes pm-enable proj_layout
proj_layout was not found.                                                                                                    [warning]
No release history was found for the requested project (proj_layout).                                  [error]
+ drush --root=/var/www/proj --yes features-revert proj_layout
The following module is missing from the file system: <em                                                  [warning]
class="placeholder">proj_layout</em>. For information about how to
fix this, see <a href="https://www.drupal.org/node/2487215">the
documentation page</a>. bootstrap.inc:1143
The feature proj_layout could not be found.                                                                          [error]
+ drush --root=/var/www/proj --yes pm-enable proj_content
proj_content was not found.                                                                                                  [warning]
No release history was found for the requested project                                                        [error]
(proj_content).
+ drush --root=/var/www/proj --yes pm-enable proj_captcha
proj_captcha was not found.                                                                                                 [warning]
No release history was found for the requested project                                                        [error]
(proj_captcha).
+ drush --root=/var/www/proj --yes features-revert proj_captcha
The following module is missing from the file system: <em                                                  [warning]
class="placeholder">proj_captcha</em>. For information about how to
fix this, see <a href="https://www.drupal.org/node/2487215">the
documentation page</a>. bootstrap.inc:1143
The feature proj_captcha could not be found.                                                                       [error]

**Comment by dashohoxha** [comment]
It seems either a recent problem with the rules module, in this file: https://cgit.drupalcode.org/rules/tree/ui/ui.plugins.inc
or a problem created by the latest version of PHP.
This breaks the propper installation of drupal, and then everything after it fails.
Any ideas on how to fix it?

**Comment by karshd3v** [comment]
There is a patch that suggests to add Declaration of `RulesRuleUI::form` as `public function form(&$form, &$form_state, $options = array(), $iterator = NULL)` and that was merged 2 months before yet drush downloading another files.

Edit: i just found out that the version of rules we are installing is stable version _rules:7.x.2.10_ and the version in which the commit is been merged is _7.x.2.x-dev_.

**Comment by karshd3v** [comment]
![screenshot from 2018-02-24 23_51_20](https://user-images.githubusercontent.com/11817859/36633525-6a6e72a8-19bd-11e8-99af-58e0b3869dd0.png)
yeah that does seems to solve that issue and i can login and see that bootstrap theme, so where can i send you the backup of website?

And there was some error with the mail module, is that really a issue?

**Comment by dashohoxha** [comment]
> where can i send you the backup of website?

It doesn't matter, send it by email if you want, or share it on google drive and send me the link.

> And there was some error with the mail module, is that really a issue?

Most probably not. Maybe you didn't give a real gmail account and password, so sending notifications failed.

**Comment by karshd3v** [comment]
I've attached screenshot and drive link in my intro discussion.

> Maybe you didn't give a real gmail account and password, so sending notifications failed.

And yes, i didn't add any mail in my settings.sh, Thank you for clarifying that.

**Comment by dashohoxha** [comment]
By the way, where did you see that suggested patch?

**Comment by karshd3v** [comment]
I saw the patch [here](https://www.drupal.org/project/rules/issues/2923477) for php 7.x compatibility.

**Comment by dashohoxha** [comment]
> I saw the patch here for php 7.x compatibility.

I would prefer to avoid the `dev` branch (`2.x-dev`) for stability reasons. If we try to install drupal later, this dev branch may be different from what it is today. Usually it has only fixes and makes things better, but you never know, it may also break the installation.

So, I would prefer to fix it with a patch, like this:
https://github.com/docker-scripts/dbox/blob/master/labdoo.make#L57-L58

Can you do it?

**Comment by karshd3v** [comment]
yeah sure, i'll try that too!
